services:
  db:
    image: postgres:17
    container_name: crudclientesgrok-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: norimorienair4614
      POSTGRES_DB: crudclientesgrok
    ports:
      - "5432:5432"
    volumes:
      - pgdata_crudclientes:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d crudclientesgrok"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata_crudclientes:
